name: bookaround
description: Un'app per l'interscambio di libri - scolastici e non.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.3.4+30


environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  # cupertino_icons: ^1.0.2
  code_field:
    git: https://github.com/emiliodallatorre/code_field.git
  google_fonts: ^2.1.0
  showcaseview: ^1.1.0

  # Firebase
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_functions: ^3.0.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  firebase_crashlytics: ^2.1.1
  firebase_dynamic_links: ^2.0.7
  firebase_analytics: ^8.2.0

  # Logica
  provider: ^5.0.0
  rxdart: ^0.27.1

  # Modelli
  json_annotation: ^4.1.0

  # Utilità
  form_field_validator: ^1.1.0
  cached_network_image: ^3.1.0
  flutter_barcode_scanner: ^2.0.0
  random_string: ^2.3.1
  shared_preferences: ^2.0.6
  timeago: ^3.1.0
  overlay_support: ^1.2.1
  webview_flutter: ^2.0.10
  tuple: ^2.0.0
  share: ^2.0.4
  package_info: ^2.0.2
  intl_phone_number_input: ^0.7.0+2

  # Grafica
  flutter_svg: ^0.22.0

  # Localizzazione
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.4
  google_maps_webservice: ^0.0.19
  # geoflutterfire:
  #   git:
  #     url: git://github.com/emiliodallatorre/GeoFlutterFire.git
  #     ref: update_deps
  geoflutterfire: ^3.0.1
  flutter_geocoder: ^0.2.2-nullsafety
  geolocator: ^7.4.0
  google_maps_flutter: ^2.0.6
  location: ^4.3.0

  # File
  image_picker: ^0.8.2


dependency_overrides:
  meta: 1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^5.0.0
  build_runner: ^2.0.6

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.1

  # flutter pub run r_flutter:generate
  r_flutter: ^0.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf


flutter_intl:
  enabled: true


flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/ic_launcher_white.png"
  image_path_android: "assets/ic_launcher_android.png"
