name: bookaround
description: Un'app per l'interscambio di libri - scolastici e non.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.6.2+39


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  # cupertino_icons: ^1.0.2
  input_code_field: ^2.0.2
  google_fonts: ^6.2.1
  showcaseview: ^3.0.0

  # Firebase
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  cloud_functions: ^5.1.4
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.5
  firebase_crashlytics: ^4.1.4
  firebase_dynamic_links: ^6.0.9
  firebase_analytics: ^11.3.4

  # Logica
  provider: ^6.1.2
  rxdart: ^0.28.0

  # Modelli
  json_annotation: ^4.9.0

  # Utilità
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_barcode_scanner: ^2.0.0
  random_string: ^2.3.1
  shared_preferences: ^2.3.2
  timeago: ^3.7.0
  overlay_support: ^2.1.0
  webview_flutter: ^4.10.0
  tuple: ^2.0.2
  share_plus: ^10.1.2
  package_info_plus: ^8.1.1
  intl_phone_number_input: ^0.7.4

  # Grafica
  flutter_svg: ^2.0.14

  # Localizzazione
  flutter_google_places_hoc081098: ^2.0.0
  # geoflutterfire:
  #   git:
  #     url: git://github.com/emiliodallatorre/GeoFlutterFire.git
  #     ref: update_deps
  geoflutterfire_plus: ^0.0.31
  flutter_geocoder: ^0.2.2-nullsafety
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  location: ^7.0.1

  # File
  image_picker: ^1.1.2


  intl: any
dependency_overrides:
  meta: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.14.1

  # flutter pub run r_flutter:generate
  r_flutter: ^0.9.0

  analyzer: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf


flutter_intl:
  enabled: true


flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/ic_launcher_white.png"
  image_path_android: "assets/ic_launcher_android.png"
