name: bookaround
description: Un'app per l'interscambio di libri - scolastici e non.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.6.2+39


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  # cupertino_icons: ^1.0.2
  input_code_field: ^2.0.2
  google_fonts: ^6.1.0
  showcaseview: ^2.0.3

  # Firebase
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  cloud_functions: ^4.5.8
  firebase_messaging: ^14.7.8
  firebase_storage: ^11.5.5
  firebase_crashlytics: ^3.4.8
  firebase_dynamic_links: ^5.4.8
  firebase_analytics: ^10.7.4

  # Logica
  provider: ^6.0.5
  rxdart: ^0.27.7

  # Modelli
  json_annotation: ^4.8.1

  # Utilità
  form_field_validator: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_barcode_scanner: ^2.0.0
  random_string: ^2.3.1
  shared_preferences: ^2.2.2
  timeago: ^3.6.0
  overlay_support: ^2.1.0
  webview_flutter: ^4.4.2
  tuple: ^2.0.2
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  intl_phone_number_input: ^0.7.4

  # Grafica
  flutter_svg: ^2.0.9

  # Localizzazione
  flutter_google_places:
    git: https://github.com/emiliodallatorre/flutter_google_places.git
  # geoflutterfire:
  #   git:
  #     url: git://github.com/emiliodallatorre/GeoFlutterFire.git
  #     ref: update_deps
  geoflutterfire_plus: ^0.0.19
  flutter_geocoder: ^0.2.2-nullsafety
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3

  # File
  image_picker: ^1.0.4


dependency_overrides:
  meta: ^1.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1

  # flutter pub run r_flutter:generate
  r_flutter: ^0.9.0

  analyzer: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf


flutter_intl:
  enabled: true


flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/ic_launcher_white.png"
  image_path_android: "assets/ic_launcher_android.png"
