on:
  push:
    branches:
      - main
name: Test build status
jobs:
  flutter_test:
    name: Test with 'flutter test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "microsoft"
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter test(s)
        run: flutter test
      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run DCM
        run: dcm analyze --ci-key="${{ secrets.DCM_CI_KEY }}" --email="${{ secrets.DCM_EMAIL }}" lib
  functions_test:
    name: Test build of Firebase Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: |
          npm install
          npm run lint
          npm run build
        working-directory: functions
